# Generated by Django 4.2 on 2023-04-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataPointModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("ts", models.DateTimeField()),
                (
                    "param",
                    models.CharField(
                        choices=[
                            ("WT", "WaterTemperature"),
                            ("AT", "AirTemperature"),
                            ("AH", "AirHumidity"),
                            ("DO", "DissolvedOxygen"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
